//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisan
    {
        public string calisanID { get; set; }
        public string calisanadi { get; set; }
        public string calisansoyadi { get; set; }
        public string calisanmail { get; set; }
        public string calisantel { get; set; }
        public string calisansifre { get; set; }
    }
}
