//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dergi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dergi()
        {
            this.dergiemanet = new HashSet<dergiemanet>();
        }
    
        public string dergiID { get; set; }
        public string ISNN { get; set; }
        public string dergiadi { get; set; }
        public string dergibasligi { get; set; }
        public string dergituru { get; set; }
        public string dergieditoru { get; set; }
        public int sayfasayisi { get; set; }
        public string yayinevi { get; set; }
        public int yayinyili { get; set; }
        public string yayinyeri { get; set; }
        public string yerID { get; set; }
    
        public virtual konum konum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dergiemanet> dergiemanet { get; set; }
    }
}
