//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi
{
    using System;
    using System.Collections.Generic;
    
    public partial class dergiemanet
    {
        public string demanetID { get; set; }
        public string uyeID { get; set; }
        public string dergiID { get; set; }
        public System.DateTime alimtarihi { get; set; }
        public System.DateTime teslimtarihi { get; set; }
        public string durumu { get; set; }
    
        public virtual dergi dergi { get; set; }
        public virtual uye uye { get; set; }
    }
}
