//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitap()
        {
            this.kitapemanet = new HashSet<kitapemanet>();
        }
    
        public string kitapID { get; set; }
        public string ISBN { get; set; }
        public string kitapadi { get; set; }
        public string kitapyazari { get; set; }
        public string kitapturu { get; set; }
        public int sayfasayisi { get; set; }
        public string yayinevi { get; set; }
        public int yayinyili { get; set; }
        public string yayinyeri { get; set; }
        public string kitapozeti { get; set; }
        public string yerID { get; set; }
    
        public virtual konum konum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kitapemanet> kitapemanet { get; set; }
    }
}
