//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_TR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sistemanalizi.Localization_TR", typeof(Localization_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇAĞDAŞ KÜTÜPHANESİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitap Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label10 {
            get {
                return ResourceManager.GetString("label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yazar Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label11 {
            get {
                return ResourceManager.GetString("label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitap Türü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label12 {
            get {
                return ResourceManager.GetString("label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayınevi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label13 {
            get {
                return ResourceManager.GetString("label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basım Yılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label14 {
            get {
                return ResourceManager.GetString("label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi İçin Arama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label15 {
            get {
                return ResourceManager.GetString("label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitap İçin Arama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label16 {
            get {
                return ResourceManager.GetString("label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇALIŞAN İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label17 {
            get {
                return ResourceManager.GetString("label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EKLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label18 {
            get {
                return ResourceManager.GetString("label18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label19 {
            get {
                return ResourceManager.GetString("label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KULLANICI GİRİŞİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GÜNCELLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label20 {
            get {
                return ResourceManager.GetString("label20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YÖNETİCİ İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label21 {
            get {
                return ResourceManager.GetString("label21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label22 {
            get {
                return ResourceManager.GetString("label22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi Başlığı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label23 {
            get {
                return ResourceManager.GetString("label23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi Türü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label24 {
            get {
                return ResourceManager.GetString("label24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi Editörü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label25 {
            get {
                return ResourceManager.GetString("label25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KİTAP İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label26 {
            get {
                return ResourceManager.GetString("label26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitap ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label27 {
            get {
                return ResourceManager.GetString("label27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISBN: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label28 {
            get {
                return ResourceManager.GetString("label28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitap Adı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label29 {
            get {
                return ResourceManager.GetString("label29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÇALIŞAN GİRİŞİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yazarı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label30 {
            get {
                return ResourceManager.GetString("label30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Türü: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label31 {
            get {
                return ResourceManager.GetString("label31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sayfa Sayısı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label32 {
            get {
                return ResourceManager.GetString("label32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayınevi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label33 {
            get {
                return ResourceManager.GetString("label33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayın Yılı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label34 {
            get {
                return ResourceManager.GetString("label34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yayın Yeri: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label35 {
            get {
                return ResourceManager.GetString("label35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kitap Özeti: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label36 {
            get {
                return ResourceManager.GetString("label36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yer ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label37 {
            get {
                return ResourceManager.GetString("label37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KİTABI EKLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label38 {
            get {
                return ResourceManager.GetString("label38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KİTABI SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label39 {
            get {
                return ResourceManager.GetString("label39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YÖNETİCİ GİRİŞİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KİTABI GÜNCELLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label40 {
            get {
                return ResourceManager.GetString("label40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜYE İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label41 {
            get {
                return ResourceManager.GetString("label41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üye ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label42 {
            get {
                return ResourceManager.GetString("label42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label43 {
            get {
                return ResourceManager.GetString("label43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyadı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label44 {
            get {
                return ResourceManager.GetString("label44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-Mail: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label45 {
            get {
                return ResourceManager.GetString("label45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label46 {
            get {
                return ResourceManager.GetString("label46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label47 {
            get {
                return ResourceManager.GetString("label47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜYEYİ EKLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label48 {
            get {
                return ResourceManager.GetString("label48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜYEYİ SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label49 {
            get {
                return ResourceManager.GetString("label49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TC Kimlik No : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜYEYİ GÜNCELLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label50 {
            get {
                return ResourceManager.GetString("label50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KİTAP EMANET İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label51 {
            get {
                return ResourceManager.GetString("label51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emanet ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label52 {
            get {
                return ResourceManager.GetString("label52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alım Tarihi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label53 {
            get {
                return ResourceManager.GetString("label53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teslim Tarihi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label54 {
            get {
                return ResourceManager.GetString("label54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durumu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label55 {
            get {
                return ResourceManager.GetString("label55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KİTAP TABLOSU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label56 {
            get {
                return ResourceManager.GetString("label56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EMANET EKLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label57 {
            get {
                return ResourceManager.GetString("label57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EMANET SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label58 {
            get {
                return ResourceManager.GetString("label58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EMANET GÜNCELLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label59 {
            get {
                return ResourceManager.GetString("label59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DERGİ EMANET İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label60 {
            get {
                return ResourceManager.GetString("label60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label61 {
            get {
                return ResourceManager.GetString("label61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DERGİ TABLOSU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label62 {
            get {
                return ResourceManager.GetString("label62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EMANETİ EKLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label63 {
            get {
                return ResourceManager.GetString("label63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EMANETİ SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label64 {
            get {
                return ResourceManager.GetString("label64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EMANETİ GÜNCELLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label65 {
            get {
                return ResourceManager.GetString("label65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DERGİ İŞLEMLERİ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label66 {
            get {
                return ResourceManager.GetString("label66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISNN: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label67 {
            get {
                return ResourceManager.GetString("label67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi Adı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label68 {
            get {
                return ResourceManager.GetString("label68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi Başlığı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label69 {
            get {
                return ResourceManager.GetString("label69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dergi Türü: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label70 {
            get {
                return ResourceManager.GetString("label70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editörü: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label71 {
            get {
                return ResourceManager.GetString("label71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DERGİ EKLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label72 {
            get {
                return ResourceManager.GetString("label72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DERGİ SİL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label73 {
            get {
                return ResourceManager.GetString("label73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DERGİ GÜNCELLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label74 {
            get {
                return ResourceManager.GetString("label74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label8 {
            get {
                return ResourceManager.GetString("label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ara : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
    }
}
