//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_EN() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sistemanalizi.Localization_EN", typeof(Localization_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Book Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search For Book benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button10 {
            get {
                return ResourceManager.GetString("button10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search For Journal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button11 {
            get {
                return ResourceManager.GetString("button11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER LOGIN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button12 {
            get {
                return ResourceManager.GetString("button12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WORKER LOGIN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button13 {
            get {
                return ResourceManager.GetString("button13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADMINISTRATOR LOGIN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button14 {
            get {
                return ResourceManager.GetString("button14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button15 {
            get {
                return ResourceManager.GetString("button15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button16 {
            get {
                return ResourceManager.GetString("button16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button17 {
            get {
                return ResourceManager.GetString("button17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button18 {
            get {
                return ResourceManager.GetString("button18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button2 {
            get {
                return ResourceManager.GetString("button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Of Book benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button3 {
            get {
                return ResourceManager.GetString("button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publisher benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button4 {
            get {
                return ResourceManager.GetString("button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button5 {
            get {
                return ResourceManager.GetString("button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Journal Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button6 {
            get {
                return ResourceManager.GetString("button6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Journal Title benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button7 {
            get {
                return ResourceManager.GetString("button7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Of Journal benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button8 {
            get {
                return ResourceManager.GetString("button8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Journal Editor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button9 {
            get {
                return ResourceManager.GetString("button9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONTEMPORARY LIBRARY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JOURNAL TRANSACTIONS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label10 {
            get {
                return ResourceManager.GetString("label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER TRANSACTIONS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label11 {
            get {
                return ResourceManager.GetString("label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BOOK TRUST TRANSACTIONS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label12 {
            get {
                return ResourceManager.GetString("label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JOURNAL TRUST TRANSACTIONS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label13 {
            get {
                return ResourceManager.GetString("label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label14 {
            get {
                return ResourceManager.GetString("label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label15 {
            get {
                return ResourceManager.GetString("label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label16 {
            get {
                return ResourceManager.GetString("label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label17 {
            get {
                return ResourceManager.GetString("label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label18 {
            get {
                return ResourceManager.GetString("label18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label19 {
            get {
                return ResourceManager.GetString("label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label20 {
            get {
                return ResourceManager.GetString("label20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WORKER TRANSACTIONS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label21 {
            get {
                return ResourceManager.GetString("label21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADMINISTRATOR TRANSACTIONS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label22 {
            get {
                return ResourceManager.GetString("label22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label23 {
            get {
                return ResourceManager.GetString("label23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book Name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label24 {
            get {
                return ResourceManager.GetString("label24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label25 {
            get {
                return ResourceManager.GetString("label25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label26 {
            get {
                return ResourceManager.GetString("label26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISBN: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label27 {
            get {
                return ResourceManager.GetString("label27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number Of Pages: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label28 {
            get {
                return ResourceManager.GetString("label28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publisher: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label29 {
            get {
                return ResourceManager.GetString("label29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YU Identity No : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label30 {
            get {
                return ResourceManager.GetString("label30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Place: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label31 {
            get {
                return ResourceManager.GetString("label31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summary: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label32 {
            get {
                return ResourceManager.GetString("label32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label33 {
            get {
                return ResourceManager.GetString("label33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD BOOK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label34 {
            get {
                return ResourceManager.GetString("label34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE BOOK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label35 {
            get {
                return ResourceManager.GetString("label35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE BOOK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label36 {
            get {
                return ResourceManager.GetString("label36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label37 {
            get {
                return ResourceManager.GetString("label37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label38 {
            get {
                return ResourceManager.GetString("label38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD USER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label39 {
            get {
                return ResourceManager.GetString("label39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE USER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label40 {
            get {
                return ResourceManager.GetString("label40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE USER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label41 {
            get {
                return ResourceManager.GetString("label41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trust ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label42 {
            get {
                return ResourceManager.GetString("label42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purchase Date: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label43 {
            get {
                return ResourceManager.GetString("label43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delivery Date: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label44 {
            get {
                return ResourceManager.GetString("label44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label45 {
            get {
                return ResourceManager.GetString("label45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BOOK TABLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label46 {
            get {
                return ResourceManager.GetString("label46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD TRUST benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label47 {
            get {
                return ResourceManager.GetString("label47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE TRUST benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label48 {
            get {
                return ResourceManager.GetString("label48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE TRUST benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label49 {
            get {
                return ResourceManager.GetString("label49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Journal ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label50 {
            get {
                return ResourceManager.GetString("label50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JOURNAL TABLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label51 {
            get {
                return ResourceManager.GetString("label51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD ESCROW benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label52 {
            get {
                return ResourceManager.GetString("label52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE ESCROW benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label53 {
            get {
                return ResourceManager.GetString("label53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE ESCROW benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label54 {
            get {
                return ResourceManager.GetString("label54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISNN: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label55 {
            get {
                return ResourceManager.GetString("label55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Journal Name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label56 {
            get {
                return ResourceManager.GetString("label56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Journal Title: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label57 {
            get {
                return ResourceManager.GetString("label57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Of Journal: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label58 {
            get {
                return ResourceManager.GetString("label58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Journal Editor: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label59 {
            get {
                return ResourceManager.GetString("label59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surname : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADD JOURNAL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label60 {
            get {
                return ResourceManager.GetString("label60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE JOURNAL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label61 {
            get {
                return ResourceManager.GetString("label61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE JOURNAL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label62 {
            get {
                return ResourceManager.GetString("label62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOCATION TABLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label63 {
            get {
                return ResourceManager.GetString("label63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER TABLE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label64 {
            get {
                return ResourceManager.GetString("label64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROCEDURES MADE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label65 {
            get {
                return ResourceManager.GetString("label65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEARCH benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label66 {
            get {
                return ResourceManager.GetString("label66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telephone Number : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat Password : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label8 {
            get {
                return ResourceManager.GetString("label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BOOK TRANSACTIONS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
    }
}
