//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphaneeEntities : DbContext
    {
        public kutuphaneeEntities()
            : base("name=kutuphaneeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calisan> calisan { get; set; }
        public virtual DbSet<dergi> dergi { get; set; }
        public virtual DbSet<dergiemanet> dergiemanet { get; set; }
        public virtual DbSet<kitap> kitap { get; set; }
        public virtual DbSet<kitapemanet> kitapemanet { get; set; }
        public virtual DbSet<konum> konum { get; set; }
        public virtual DbSet<uye> uye { get; set; }
        public virtual DbSet<yonetici> yonetici { get; set; }
        public virtual DbSet<tblkitap_Log> tblkitap_Log { get; set; }
    }
}
