//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkitap_Log
    {
        public int ID { get; set; }
        public string kitapID { get; set; }
        public string ISBN { get; set; }
        public string kitapadi { get; set; }
        public string kitapyazari { get; set; }
        public string kitapturu { get; set; }
        public Nullable<int> sayfasayisi { get; set; }
        public string yayinevi { get; set; }
        public Nullable<int> yayinyili { get; set; }
        public string yayinyeri { get; set; }
        public string kitapozeti { get; set; }
        public string yerID { get; set; }
        public string log_islem { get; set; }
        public System.DateTime log_tarih { get; set; }
    }
}
