//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi
{
    using System;
    using System.Collections.Generic;
    
    public partial class uye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uye()
        {
            this.dergiemanet = new HashSet<dergiemanet>();
            this.kitapemanet = new HashSet<kitapemanet>();
        }
    
        public string uyeID { get; set; }
        public string uyeadi { get; set; }
        public string uyesoyadi { get; set; }
        public string uyemail { get; set; }
        public string uyetel { get; set; }
        public string uyesifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dergiemanet> dergiemanet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kitapemanet> kitapemanet { get; set; }
    }
}
