//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemanalizi
{
    using System;
    using System.Collections.Generic;
    
    public partial class yonetici
    {
        public string yoneticiID { get; set; }
        public string yoneticiadi { get; set; }
        public string yoneticisoyadi { get; set; }
        public string yoneticimail { get; set; }
        public string yoneticitel { get; set; }
        public string yoneticisifre { get; set; }
    }
}
